name: CI on Sleakops

on:
  push:
    branches:
      - main
  pull_request: 
    types: [opened, reopened, ready_for_review]
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_build_main:
    # needs: [test]
    if: |
      (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:

    - name: Install SleakOps CLI
      run: pipx install sleakops

    - name: Run SleakOps build
      env:
        SLEAKOPS_KEY: ${{ secrets.SLEAKOPS_KEY }}
      run: sleakops build -p sleakops-demo -b main -e demo --prov aws-demo -w

    - name: Run SleakOps deploy
      env:
        SLEAKOPS_KEY: ${{ secrets.SLEAKOPS_KEY }}
      run: sleakops deploy -p sleakops-demo -e demo  -e demo -prov aws-demo -w
